# Generated by Django 4.2.29 on 2026-04-06 18:08
# Migrated to CKEditor 5 field type

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policysection',
            name='body',
            field=CKEditor5Field(config_name='default'),
        ),
    ]
