# Generated by Django 4.2.29 on 2026-04-06 18:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policysection',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
