# Generated by Django 4.2.21 on 2026-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Global Configuration', 'verbose_name_plural': 'Global Configuration'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_color',
            field=models.CharField(default='#b00216', help_text='Hex color code for the alert banner background (e.g. #b00216)', max_length=7),
        ),
    ]
