# Generated by Django 4.2.29 on 2026-04-06 17:12

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_alter_sitesettings_options_sitesettings_alert_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1600x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
