# Generated by Django 4.2.29 on 2026-04-06 17:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0003_heroslide_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='alert_color',
            field=colorfield.fields.ColorField(default='#b00216', help_text='Color for the alert banner background', image_field=None, max_length=25, samples=None),
        ),
    ]
