# Generated by Django 4.2.29 on 2026-04-06 17:47

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0004_alter_sitesettings_alert_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home Feature (Why Choose Us)',
                'verbose_name_plural': 'Home Features (Why Choose Us)',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'History Timeline Item',
                'verbose_name_plural': 'History Timeline Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('about', 'About Us'), ('why_us', 'Why Choose Us'), ('history', 'Our History')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home Stat',
                'verbose_name_plural': 'Home Stats',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_headline',
            field=models.CharField(default='Where the Good<br><em>Become Great</em>', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default='Private music lessons for all ages — inspiring students for over 60 years', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stats_description',
            field=models.TextField(blank=True, default="Since 1964, we've helped Charlotte families discover the joy of music."),
        ),
    ]
