# Generated by Django 4.2.29 on 2026-04-06 18:31

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0006_alter_heroslide_cropping_alter_homesection_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1600x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
