# Generated by Django 4.2.29 on 2026-04-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0013_swap_cropping_for_focal_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='image_focal_y_mobile',
            field=models.PositiveSmallIntegerField(default=50, help_text='Mobile focal point (0=top, 50=center, 100=bottom).'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Optional portrait-oriented image shown on phones (<640 px wide). Falls back to the desktop image if empty.', null=True, upload_to='hero_mobile/'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='image_focal_y_mobile',
            field=models.PositiveSmallIntegerField(default=50, help_text='Mobile focal point (0=top, 50=center, 100=bottom).'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Optional image for mobile (<768 px). Falls back to the desktop image if empty.', null=True, upload_to='home_mobile/'),
        ),
    ]
