# Generated by Django 4.2.29 on 2026-04-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_swap_cropping_for_focal_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='image_focal_y_mobile',
            field=models.PositiveSmallIntegerField(default=50, help_text='Mobile focal point (0=top, 50=center, 100=bottom).'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='photo_mobile',
            field=models.ImageField(blank=True, help_text='Optional image for mobile (<576 px). Falls back to the desktop photo if empty.', null=True, upload_to='faculty_mobile/'),
        ),
    ]
