# Generated by Django 4.2.21 on 2026-04-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_galleryphoto_image_focal_y_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='image_focal_x_mobile',
            field=models.PositiveSmallIntegerField(default=50, help_text='Horizontal focal point on phones (0=left, 50=center, 100=right).'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image_focal_y_mobile',
            field=models.PositiveSmallIntegerField(default=50, help_text='Vertical focal point on phones (0=top, 50=center, 100=bottom).'),
        ),
    ]
