# Generated by Django 4.2.29 on 2026-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecitalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Recital Program', max_length=200)),
                ('pdf', models.FileField(upload_to='programs/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recital Program',
                'verbose_name_plural': 'Recital Program',
            },
        ),
    ]
